/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.vectorrally.app;


public class App {
    public static void main(String[] args) {
      System.out.println("Hello world!");
    }
}
